[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path  = 'forge-cache'
solc-version = "0.8.24"
via_ir = true
optimizer = true
optimizer-runs = 200

rpc_endpoints = { mainnet = "https://rpc.ankr.com/eth", holesky = "https://rpc.ankr.com/eth_holesky" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
